### ISSUE TITLE
Latest version v5.2.1 breaks new assignment  

### ISSUE THREAD

**Issue by radames** [d3/d3-delaunay#101]
Not sure if the news pushes to static from https://github.com/d3/d3-delaunay/commit/778acc9ad3162b1ea032f975edf307a26a206bf3 were supposed to cause this error. 

But now many `d3-delaunay@5` are broken now if the initializaiont is done with `new` assignments
Was it an expected result?  shall we move to  

```const delaunay = d3.Delaunay.from(particles); ```

instead of ?

```const delaunay = new d3.Delaunay.from(particles); ```

Broken examples:
https://observablehq.com/@d3/hover-voronoi
https://observablehq.com/@fil/mobility-landscapes

**Comment by mourner** [comment]
I think the error is expected — you should only use `new` in combination with classes (`new d3.Delaunay.from` is incorrect), while `from` is a factory function that does instantiation internally.

**Comment by Fil** [comment]
Thanks for the links to the broken examples (in my garden :^) ). I agree
that those examples are wrong — let's hope there are not too many of them
in the wild.

-- Fil

**Comment by radames** [comment]
wonderful! thanks for the response, I've already fix some of my projects using the old `new` assignment.  If I come across other notebooks on observables I'll send comments! Shall I close this issue?

**Comment by Fil** [comment]
unfortunately we can't search observable for "new d3.Delaunay.from"

**Comment by radames** [comment]
> unfortunately we can't search observable for "new d3.Delaunay.from"

I've tried the quoted search, unfortunately it doesn't do the full matching search :(
