### ISSUE TITLE
What's the reason for the duplication of the data in `voronoi.vectors`?

### ISSUE THREAD

**Issue by vchizhov** [d3/d3-delaunay#102]
Why does `voronoi.vectors` duplicate the rays on the hull? It should be enough to just store a ray once per hull edge, then we can access the rays at hull vertex `i` through `hull[i]` and `hull[i+1]`. 

EDIT: In fact the description `An Uint64Array [vx0, vy0, wx0, wy0, …]` is misleading, as instead it is a `Float64Array`, and the rays are not even quadruples per vertex, instead it seems like the construction of the rays simply does redundant overwrites of possibly previously filled in rays.

**Comment by Fil** [comment]
I'm not sure how to answer your question, please feel free to send a PR with optimized code. And I've now fixed the mistake in the README, thank you for the report.
