### ISSUE TITLE
Error with es6 worker + es6 modules

### ISSUE THREAD

**Issue by chris-kruining** [d3/d3-delaunay#111]
Hi,

I'm getting the following error when trying to include your lib in js worker (paint-worklet to be exact).

```
Uncaught (in promise) ReferenceError: self is not defined
```

Can you either chain and or change the `self` to `globalThis` (is supported by all relevant browsers as far as I am aware).

Or even better, if I can bother you with this job, create a delaunay.min.esm so I can just use es6 modules as is :D

Thanks in advance!!!

**Comment by chris-kruining** [comment]
btw, this is how I import the code, the docs tell me that a `d3` global is created, so to get that I have 

```
import 'https://unpkg.com/d3-delaunay@5.3.0/dist/d3-delaunay.js';

console.log(d3);
```

but I never reach my console log due to the error

**Comment by Fil** [comment]
this works for me:
~~~
cat test.html
<script type=module>
import 'https://unpkg.com/d3-delaunay@5.3.0/dist/d3-delaunay.js';
console.log(d3);
</script>
~~~

**Comment by chris-kruining** [comment]
test.html
```html
<script type="module">
    await CSS.paintWorklet.addModule('gradient.js');
</script>
```
gradient.js
```es6
import 'https://unpkg.com/d3-delaunay@5.3.0/dist/d3-delaunay.js';
console.log(d3);
```

Throws the error, because workers and/or worklets do not have a global variable `self`

**Comment by chris-kruining** [comment]
aah correction, worklets specifically, workers work fine.

this creates a worker, and works as intended
```html
<script type="module">
    const w = new Worker('gradient.js', { type: 'module' });
</script>
```

where as my previous comment creates a worklet, which gives the error of the `self` variable being `undefined`

**Comment by Fil** [comment]
hmmm I wonder if upgrading rollup would suffice?
Compare the boilerplate at the top of https://unpkg.com/d3@5.16.0/dist/d3.js and https://unpkg.com/d3@6.0.0/dist/d3.js ; the difference was introduced by our upgrade to rollup:"2" and specifically https://github.com/rollup/rollup/releases/tag/v2.23.0

It's something that's yet to deploy in all the modules.

**Comment by chris-kruining** [comment]
can I possibly bother you with the question of quickly making a build with the new rollup? or is that not feasible?

**Comment by Fil** [comment]
I have a simpler test:

~~~js
import 'https://unpkg.com/d3@6';
console.log(d3); // {the d3 object} 👍
~~~

~~~js
import 'https://unpkg.com/d3@5';
console.log(d3); // ReferenceError: self is not defined 💣
~~~

So I guess the next releases will work. In the meantime you might want to load d3@6

**Comment by Fil** [comment]
Related: https://github.com/d3/d3/pull/3366

**Comment by chris-kruining** [comment]
Thanks!!! works like a charm!

**Comment by Fil** [comment]
leaving open so I'll be happier to close it with the proper dependency upgrade :)

**Comment by chris-kruining** [comment]
ok. :D

**Comment by chris-kruining** [comment]
if by any chance you are curious what I need this lib for: I'm trying to replicate adobe illustrator's freeform gradient in the browser, this is to not limit the options of the designers.

![image](https://user-images.githubusercontent.com/5786905/92252932-36029000-eecf-11ea-9715-dc06913da59d.png)

As you can see, I still need to find a way to actually blend between the polygons :D

**Comment by Fil** [comment]
Should be fixed by https://github.com/d3/d3-delaunay/pull/113

**Comment by chris-kruining** [comment]
> Oh oh! You would do https://observablehq.com/@fil/walk-on-spheres-worker in gradient.js?

sorry for the late response, I seem to have overlooked this on my vacation.

I don't believe I would use the tatic used in your link as the 2dcontext provided by a paintworklet, while intended to be similar, is not the same as a canvas. One of the differences is no ability to draw pixel per pixel. In this case meaning that I need some nasty workaround to calculate each pixels color based on a polygon somehow.

my current thinking is to use what I have above and then somehow place some linear gradients on the edges.

**Comment by Fil** [comment]
Your approach made me curious about this spec and I wrote a helper function to create and update paintworklets https://observablehq.com/@fil/hello-paintworklet

**Comment by chris-kruining** [comment]
nice! thanks for the mention :D

Maybe I'll make a post if / when I actually manage to make this gradient shader without per-pixel calculations :P

**Comment by Fil** [comment]
fixed in d3-delaunay@6
