### ISSUE TITLE
Would it be possible to make this work with a convex hull boundary for the Voronoi cells?

### ISSUE THREAD

**Issue by JobLeonard** [d3/d3-delaunay#112]
So I've been interested in doing experiments with voronoi "treemaps".

![image](https://user-images.githubusercontent.com/259840/92408271-415af300-f13d-11ea-9e91-cdf316eba57b.png)

So before you say "well, we already have https://github.com/Kcnarf/d3-voronoi-treemap for that", that is true in principle, but the experiments I have in mind are a bit more more "raw" than this data visualization.

For example, I would like to try out what voronoi stippling in a "multiple pass" fashion would look like (first "stipple" with *N* points, then inside each of those ten cells "stipple" with another *N* points, and keep recursing like this until a desired number of total points is reached).

Looking at the currently existing methods, `delaunay.renderHull` already gives me a convex hull of all points, so if I start with a set of points defining a convex hull, then ensure that all points are inside of it, the *triangulation* part works out fine. But what I basically am asking for is be able to generate voronoi cells with this convex hull as its bounding box. Would it be complicated to do such a thing?

EDIT: so to be clear, the question is "is this already possible with the current library somehow, or would it require a bunch of funky hacks?"

**Comment by Fil** [comment]
Here's my take on this https://observablehq.com/@fil/clip-lloyd
I'm using https://github.com/mfogel/polygon-clipping to clip the cells to the original convex hull.

**Comment by JobLeonard** [comment]
> Made to celebrate the release of d3-delaunay@6!

I feel like I'm getting two presents at once! :D
