### ISSUE TITLE
context.moveTo and context.lineTo implementation

### ISSUE THREAD

**Issue by MLouis8** [d3/d3-delaunay#133]
Hello,
I'm using canvas.getContext('2d') as a context for displaying a voronoi diagram.
But when I call voronoi.render([context]) the following error comes up :
"TypeError: context.moveTo is not a function"
How can I use d3-delaunay API without creating my own context ?

here is my code:
<script src="https://gist.github.com/MLouis8/390f882dd72d0ee4fb25ddde97b1172b.js"></script>

thanks

**Comment by Fil** [comment]
try `voronoi.render([context])` ; the brackets indicate that the context is optional.
