### ISSUE TITLE
Edges that both sides are clipped sometimes will not be identified as voronoi neighbor

### ISSUE THREAD

**Issue by UnluckyNinja** [d3/d3-delaunay#137]
![image](https://user-images.githubusercontent.com/1270155/222190664-4cadce48-c2c6-4f2c-ac19-5237d93ed8e0.png)
Reproduction: https://observablehq.com/d/3e65ad730f4712fc
Green lines visualize voronoi neighbors, red ones visualize delaunay-only neighbors.
If you change the first 3 parameters, cell 0-4, 1-5, 3-7, 2-6 are no longer neighbors occasionally.
It seems it only happens on both sides clipped edges. Edges that at least one end of it resides in viewbox are fine.

**Comment by Fil** [comment]
Yes. It happens on https://github.com/d3/d3-delaunay/blob/2196b80926a0b68e40c1f416b634f8a4a0a11208/src/voronoi.js#L154

I have also reproduced the issue here: https://observablehq.com/@d3/voronoi-neighbors-137

**Comment by UnluckyNinja** [comment]
Tried the fixed version from #138 in my notebook. It's consistently and correctly recognized for the clipped edges now.
Very much appreciated.
