### ISSUE TITLE
Flatten hull into an array of indices

### ISSUE THREAD

**Issue by mourner** [d3/d3-delaunay#16]
In Delaunator, the convex hull is kept as a circular doubly linked list internally for convenience/performance during the Delaunay sweep phase, but I think there's no point in exposing it like this in a public API — it would be simpler to flatten it after Delaunay construction and remove the "Node" section in Voronator API reference.

The only question is whether we should do this in Delaunator (and expose `hull` as a `Uint32Array` publicly), or Voronator.

**Comment by mbostock** [comment]
Agree. That would be cleaner! 👍

**Comment by mbostock** [comment]
I’ve tinkered a little bit with this in the [flat-hull branch](https://github.com/d3/d3-delaunay/tree/flat-hull). My first inclination was that the hull should be represented simply as an array of point indexes [*i0*, *i1*, …]. But this isn’t a convenient representation for rendering the Voronoi—the Voronoi needs to know the triangle that includes the edge between points *i* and *i* + 1 so it can look up the circumcenter. So I think it needs to be a flat array of triangle vertex indexes, where each triangle vertex *i*’s half-edge is the next vertex on the convex hull.
