### ISSUE TITLE
Define Voronoi diagram for entirely-collinear input?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-delaunay#20]
This throws an error (No Delaunay triangulation exists for this input):

```
Delaunay.from([[0, 0], [1, 1], [2, 2]])
```

But like #19, there is a valid Voronoi diagram for this input! The problem is that all the cells have infinite sides and no points. Hrm.

**Comment by HussainMirahmadi** [comment]
this issue along with this iterables complexity made me compare the performance of 'd3-delaunay' with 'd3-voronoi' to see is the promised performance difference worth this much effort to use first over the second , after feeding them with sets of points with different sizes , the results where equal an as follow :
0.5 Million points in 1000x1000 space : ~7051 milisecond
50 points in 100x100 space: ~50 milisecond

**Comment by Fil** [comment]
Fixed by https://github.com/d3/d3-delaunay/commit/2ee9847155f02a4a39ed9d251ed18b98a46f96a2
