### ISSUE TITLE
voronoi.index of triangle vertexes?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-delaunay#34]
What if voronoi.index pointed to the first triangle vertex for a given cell, and then we used the halfedge traversal algorithm lazily? Then we wouldn’t need to precompute voronoi.edges.

**Comment by redblobgames** [comment]
This is what I do, except I point to the first(*) halfedge. From the halfedge I can get the triangle vertex but I can also traverse in other fun ways.

(*) I've simplified a bit more by adding “ghost” triangles around the convex hull. These link to an “infinity” site. With the ghost elements, halfedges[e] is never -1, which simplifies some of the traversal logic. In exchange, whenever drawing I need to test for ghosts, but overall it's been a big win for my projects.
