### ISSUE TITLE
Can't render Voronoi diagram for particular set of points

### ISSUE THREAD

**Issue by chnn** [d3/d3-delaunay#37]
Hello,

I'm having trouble rendering a Voronoi diagram for a set of points with a certain structure. The set of points looks like this:

![voronoi](https://user-images.githubusercontent.com/638955/38575493-697b4658-3cb0-11e8-9980-7321fd2fb32c.png)

[Here](https://beta.observablehq.com/@chnn/d3-delaunay-test) is a notebook that describes the issue in more detail.

This sounds like it might be related to #20, though no error is thrown in this case.

**Comment by mourner** [comment]
Hmm, maybe browser-specific? I'm seeing results for both in your notebook:

![image](https://user-images.githubusercontent.com/25395/38578318-445f626c-3d0c-11e8-8db6-1ff7f98d31d4.png)

Are there any errors in the console?

**Comment by chnn** [comment]
Ah, great! I had not thought to try another browser.

I was using Firefox 59.0.2 on macOS. It throws no errors in the console.

**Comment by mourner** [comment]
When I replace the render line to this:

```js
voronoi.render({moveTo: console.log, lineTo: console.log});
```

I see some weird huge values, which Firefox probably can't handle:

```js
664.4831297076121 -31.1735912402529
672.3576712448785 -72.0304244992434
664.4831297076121 -31.1735912402529
680.819008033027 -16.631376838536138
633.5412543174806 393.00884225846926
23813793908081870 21199061956212450
121.41720113242671 -231.98418498812734
-26277289829606750 -23392068365475628
121.41720113242671 -231.98418498812734
154.39760765467472 -237.02142549637443
...
```

@mbostock I suspect this is some unhandled edge case in the clipping code?

**Comment by mbostock** [comment]
Confirmed. If you zoom out in Chrome:

![image](https://user-images.githubusercontent.com/230541/38582143-b469c942-3cc3-11e8-93b2-ebd1ee5aed36.png)

This is almost certainly caused by the collinear points, but I don’t know yet whether it’s a problem with the construction of the Delaunay hull or with Voronoi clipping.

**Comment by mbostock** [comment]
The issue here is that because the points are (nearly) collinear, some of the circumcenters have huge coordinates. We’re not doing anything special to handle these huge coordinates in *voronoi*.render, but we probably should clip the line segments before rendering, as we do in *voronoi*.renderCell.

**Comment by mbostock** [comment]
![image](https://user-images.githubusercontent.com/230541/38583384-afa36658-3cc7-11e8-88f3-7a23b0041232.png)

**Comment by mbostock** [comment]
Unfortunately, it looks like *voronoi*.renderCell is still broken with this fix:

![image](https://user-images.githubusercontent.com/230541/38583414-caf46948-3cc7-11e8-9130-8f20566e0caf.png)

**Comment by mbostock** [comment]
Made some progress, but now I’m stuck.

![image](https://user-images.githubusercontent.com/230541/38584942-ec221b42-3ccc-11e8-91c7-d83c709d10a2.png)
