### ISSUE TITLE
Clipped Voronoi cells sometimes have zero-length edges.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-delaunay#42]
Not sure if this is a bug per se, but it would be nice to avoid them.

**Comment by mourner** [comment]
Is there an example of this?

**Comment by Fil** [comment]
![image](https://user-images.githubusercontent.com/7001/59964697-3bf79580-9504-11e9-969e-fb3345b3b098.png)

https://observablehq.com/d/93c4555b681dcf86

**Comment by Fil** [comment]
testing for `(points[i] !== points[i-2] || points[i+1] !== points[i-1])` in https://github.com/d3/d3-delaunay/blob/master/src/voronoi.js#L103 does the trick; but I don't know the price in terms of speed (possibly negligible?).
