### ISSUE TITLE
Update observable demo to current version of the module

### ISSUE THREAD

**Issue by Fil** [d3/d3-delaunay#43]
https://beta.observablehq.com/d/3b28638926bcac75 fixes the last part of https://beta.observablehq.com/@mbostock/the-delaunays-dual

(sorry for the weird alignments, they're _prettier_)

**Comment by mourner** [comment]
Fixed by #44

**Comment by mbostock** [comment]
Probably not going to do this, sorry.

**Comment by mbostock** [comment]
Done.
