### ISSUE TITLE
voronoi.find radius?

### ISSUE THREAD

**Issue by martgnz** [d3/d3-delaunay#45]
In [d3-voronoi](https://github.com/d3/d3-voronoi#diagram_find) *voronoi*.**find** accepts a third argument, *radius*, which returns the nearest point from that distance. In this case the third argument *i*, specifies the *index* where the search starts.

I find the radius useful for creating distance-limited interactions. Is this something that you may consider adding?

**Comment by martgnz** [comment]
My doubt was in regards implementing something like your [block](https://bl.ocks.org/Fil/425346f63abddee5fea3fdcb76904820) but with a distance-limited interaction. Using d3-voronoi you can just a third argument for the radius.

How would you do something like that with this library? For example, by passing a number close to the current index?

**Comment by Fil** [comment]
You can always check the distance between your point and the site found, something like (pseudocode):
```
v.find_with_radius = function(x,y, radius) {
  n = v.find(x,y);
  if (n !== null && distance(site[n], [x,y]) < radius) return n;
}
```

But I wonder if it should not be put into the API in lieu of [site]. @mbostock we can prepare a PR if you agree with this change.

**Comment by mbostock** [comment]
The radius (distance) test happens after finding the closest site; it doesn’t optimize the search. So, you should perform your radius test after calling find, as @Fil suggests.

The reason that find takes a starting index is that I don’t want find to mutate the internal state of the delaunay instance (as d3-voronoi does). By keeping the internal state immutable, you have greater flexibility in employing your search optimizations.
