### ISSUE TITLE
Get cells on either side of an edge

### ISSUE THREAD

**Issue by EternalDeiwos** [d3/d3-delaunay#47]
d3-voronoi has an edge object with `edge.left` and `edge.right` properties to get the index of the cell on either side.

Is there any chance you'd consider adding something similar to d3-delaunay? I've been trying to figure it out for the last while without success.

**Comment by mbostock** [comment]
You can get the adjacent Voronoi cells using [*delaunay*.neighbors](https://github.com/d3/d3-delaunay/blob/master/README.md#delaunay_neighbors). This is used to implement *delaunay*.find, for example. You can also access the internal data structures directly if you prefer, as described in this guide: https://redblobgames.github.io/delaunator/
