### ISSUE TITLE
Upgrade to delaunator@3.

### ISSUE THREAD

**Issue by JobLeonard** [d3/d3-delaunay#50]
More performance!

See also #49 ;)

**Comment by mbostock** [comment]
Yes, I would like to do this, I just haven’t found the time.

**Comment by mourner** [comment]
@JobLeonard you only need the `delaunator.hull` array, which is generated at the end of the constructor:

https://github.com/mapbox/delaunator/blob/c20ef21ef78b0dd9689aa13070010f8a3b5c5a51/index.js#L218-L222

**Comment by mbostock** [comment]
I’ve tried a few times to upgrade this library to Delaunator v3, and my brain just can’t keep track of the different meaning of the indexes to get it working. Like, the old code:

```js
// For points on the hull, index both the incoming and outgoing halfedges.
let node0, node1 = hull;
do {
  node0 = node1, node1 = node1.next;
  inedges[node1.i] = node0.t;
  outedges[node0.i] = node1.t;
} while (node1 !== hull);
```

I know I can iterate over the hull array, but I can’t figure out how to compute the equivalents to *node*.i and *node*.t in the new data structure.

```js
for (let i = 0, h0, h1 = hull[hull.length - 1]; i < hull.length; ++i) {
  h0 = h1, h1 = hull[i];
  inedges[???] = ???;
  outedges[???] = ???;
}
```

**Comment by mbostock** [comment]
In particular, I think the new hull data structure doesn’t tell me the halfedge indexes of the convex hull—just the point indexes. So, I don’t think there’s an easy way to initialize inedges[i] with the halfedge index of the hull edge for a point *i* on the hull.

**Comment by mourner** [comment]
All right, will look into this...

**Comment by Fil** [comment]
Please test PR #59.
