### ISSUE TITLE
Find Voronoi cell and neighbors

### ISSUE THREAD

**Issue by igagen** [d3/d3-delaunay#51]
Is there a way to find the voronoi cell covering a point? And once you have a cell, is there a way of getting all the neighboring cells?

**Comment by mbostock** [comment]
[*delaunay*.find](https://github.com/d3/d3-delaunay#delaunay_find)

[*delaunay*.neighbors](https://github.com/d3/d3-delaunay#delaunay_neighbors)

**Comment by igagen** [comment]
I’m asking about the Voronoi cell and it’s neighbors, not the Delaunay triangle at a point. Is there a simple way to go from Delaunay triangle and neighbors to Voronoi?

**Comment by igagen** [comment]
Got it, I wasn’t sure if the Voronoi indices matched the Delaunay indices. Thanks!
