### ISSUE TITLE
Production build includes new ECMAScript features.

### ISSUE THREAD

**Issue by SokichiFujita** [d3/d3-delaunay#52]
Because of `d3-delaunay` uses a lot of ECMAScript new and experimental feature (e.g. class, exponential operator) for production build, it causes issues for production use.

Do you have a plan to use transpiler like babel to build a production module?

**Comment by mbostock** [comment]
I do not, sorry!

**Comment by SokichiFujita** [comment]
Got it. Thanks. I consider another plan.

**Comment by echap** [comment]
Hello,
I know you do not intend to transpile this plugin, but I just want to add a thumb up on the interest of doing it. Indeed this makes this awesome tool unavailable using react native // common js based stuff.

**Comment by mourner** [comment]
Note that it also depends on generators, so transpiling it would probably make a part of the functionality a lot slower.
