### ISSUE TITLE
delaunay.find fails when i is a coincident point.

### ISSUE THREAD

**Issue by jens-ox** [d3/d3-delaunay#55]
I'm working with a set of lines that sometimes have coincident start points. I use d3-delaunay to find the nearest point to the cursor in order to highlight the line this point belongs to.

![Screenshot of graph](https://user-images.githubusercontent.com/5368029/53726748-f046b080-3e6e-11e9-9bd8-d64b2b2ada7c.png)

If it occurs that there is a point coincident to the first point of the first line, `inedges[0]` will be -1. Therefore, `find(x, y, i = 0)` will return -1 independent of `x` and `y` (because of how the `_step` function is implemented) &mdash; but `find(x, y, i = 1)` will not return -1 (or maybe only for `i = 2, 3,...`).

**Question**:
- Should this case be handled by me (by iteratively incrementing `i` and calling `find(x, y, i)`) or by d3-delaunay?

**Comment by mbostock** [comment]
This is a bug.

**Comment by EduardoAC** [comment]
Any progress on solving this bug?

**Comment by mbostock** [comment]
If there were progress on solving this bug, you would see it here.

**Comment by Fil** [comment]
This seems to be working:
~~~
    if (inedges[i] === -1) {
      const l = points.length / 2;
      return (i + 1 + (l - 1) * Math.random() | 0) % l;
    }
~~~

It makes sure that from a coincident point i we jump to somewhere else than i, at random so it doesn't get stuck in an infinite loop.

**Comment by Fil** [comment]
@jens-ox let us know if you can confirm on your test case
