### ISSUE TITLE
Please transpile `dist/delaunay.js`

### ISSUE THREAD

**Issue by boygirl** [d3/d3-delaunay#66]
My library currently depends on `d3-voronoi`, and I'm trying to upgrade to `d3-delaunay` for performance improvements. Unfortunately, the lack of a transpiled target is a blocker. Transpiling it myself with webpack works for publishing the `dist` version of my library, but I'm currently also providing a transpiled `lib` which is how most of my users consume my library. At the moment, including this package would force all of those people to alter their builds to accommodate the change.

**Comment by mbostock** [comment]
Sorry, but I do not support older environments.
