### ISSUE TITLE
Add an update method for relaxation algorithms

### ISSUE THREAD

**Issue by mourner** [d3/d3-delaunay#68]
Delaunator v4 got [an update method](https://github.com/mapbox/delaunator#delaunayupdate) to update triangulation after editing coordinates in place, avoiding a lot of new memory allocations for use cases like the Lloyd's algorithm (see https://github.com/mapbox/delaunator/issues/36). 

It would be great to make a corresponding change in `d3-delaunay` as well. The `Delaunay` class would have to hold on to the whole `delaunator` object then (instead of just `triangles`, `halfedges` and `hull`), and update `inedges/outedges` after calling `delaunator.update` in a potential `update` method.

**Comment by Fil** [comment]
Fixed by https://github.com/d3/d3-delaunay/commit/5dcc818e2e4a64a85fe652d8742a961b9d1015f0
