### ISSUE TITLE
Math problem with `voronoi.cellPolygon`

### ISSUE THREAD

**Issue by nkint** [d3/d3-delaunay#72]
#### What 
Some wrong `voronoi.cellPolygon` results maybe related to floating points precision.

#### How 
Hi! I've tried to reproduce the famous @mbostock [Mike & Mario sketch rotating-voronoi](https://observablehq.com/@mbostock/rotating-voronoi).

But I noticed some problems. Talking with @Fil in the d3 slack he came up with a observable nootbook to reproduce the problem.

#### MWE to show the bug:
https://observablehq.com/d/bd8a95abd9a01c79

#### Notes:
I've tried with both d3-delaunay version 5.0.2 and 4.0.2 

@Fil added this note:
> change 253.74999999999997 to 253.75

Thanks!

**Comment by Fil** [comment]
Maybe linked to precision issues like https://github.com/mapbox/delaunator/issues/43

**Comment by mourner** [comment]
Yeah, this is almost certainly https://github.com/mapbox/delaunator/issues/43 — let's track it there.
