### ISSUE TITLE
Voronoi cells not rendered properly with many points

### ISSUE THREAD

**Issue by spandl** [d3/d3-delaunay#79]
An observable sketch was created for better demonstration:
https://observablehq.com/@ralph_spandl/voronoi-cell-test

When having many points (10K) `voronoi.renderCell` seems to have issues rendering the cells properly.

Canvas was used for this purpose.

**Comment by mbostock** [comment]
I expect this is a duplicate of mapbox/delaunator#43. The problem can be fixed by adding random jitter to the input points. Without jitter:

![image](https://user-images.githubusercontent.com/230541/61488569-6864cd00-a95d-11e9-86e5-78a3412382fe.png)

With jitter:

![image](https://user-images.githubusercontent.com/230541/61488600-7fa3ba80-a95d-11e9-9f6e-29c913c8a06f.png)

```js
points = (await d3.json("https://gist.githubusercontent.com/spandl/4392601e73666c4ea514aefeb0cb7397/raw/88780f991d6fb9b839420397960e2bcece524398/d3-data")).map(({x, y}) => ({x: x + Math.random() / 1000, y: y + Math.random() / 1000}))
```

**Comment by mbostock** [comment]
Here’s the jittered workaround:

https://observablehq.com/d/c0ba7502f2c7ac68

**Comment by spandl** [comment]
Fantastic. This did solve the problem indeed.

![image](https://user-images.githubusercontent.com/5740594/61490251-7ffe7e80-a97a-11e9-94c3-1e15f5634c4b.png)

I also updated the sketch with the checkbox to show the effect:
https://observablehq.com/@ralph_spandl/voronoi-cell-test

Thanks. I am closing.

**Comment by Fil** [comment]
I've tried to dig a bit in this case, and isolated one problem (there might be others)
https://observablehq.com/d/d03f1a78687dd953

The two first points have the same x coordinate, and their y coordinate differs by 1e-14.

Rounding all the points to 1e-12 precision solves the problem:
https://observablehq.com/d/b219d92fae85fc9b

**Comment by spandl** [comment]
I can confirm that rounding solved my issue as well. In my case this was the easiest solution, there was no need for more precision.
