### ISSUE TITLE
Duplicated vertex in output Voronoi polygons

### ISSUE THREAD

**Issue by jheer** [d3/d3-delaunay#83]
At least for the case of two input points, the returned cell polygons may duplicate the start/end-point vertex.

```js
const points = [[10, 10], [20, 10]];
const delaunay = Delaunay.from(points);
const voronoi = d.voronoi([0, 0, 30, 20]);
console.log(voronoi.cellPolygon(0).join(' -> '));
// 15,20 -> 0,20 -> 0,0 -> 15,0 -> 15,20 -> 15,20
```

**Comment by mbostock** [comment]
Related #42?

**Comment by Fil** [comment]
Duplication is not detected when it happens with the first and last points.
https://github.com/d3/d3-delaunay/commit/4c2a05fa790eace6c818e3fbe907693bed2bd7b4#diff-2de452b04d4af7398be755b8afb55fb2R105

Not sure how to write this efficiently… not calling closePath() maybe if last===first?

**Comment by Fil** [comment]
> not calling closePath() maybe if last===first?

Doing so works, but it is not so satisfying when you see the SVG path that just doesn't end with Z.
I propose instead https://github.com/d3/d3-delaunay/pull/84
