### ISSUE TITLE
how to get all edges of voronoi diagram?

### ISSUE THREAD

**Issue by bianbian-org** [d3/d3-delaunay#94]
like https://github.com/d3/d3-voronoi#diagram  edges
or
https://github.com/d3/d3-voronoi#edge

**Comment by bianbian-org** [comment]
I have found #91

**Comment by Fil** [comment]
This notebook might clarify how this can be done:
https://observablehq.com/d/045ae1b3e80973dc

**Comment by bianbian-org** [comment]
Thanks @Fil
